name: Scout

on:
  workflow_run:
    workflows: ["Build and Deploy"]
    types:
      - completed

jobs:
  scout:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - name: Trigger local service
        run: sudo /opt/watchdog/bin/watchdog update
